version: '3.8'
services:
  mint-obs-api:
    build: 
      context: .
      dockerfile: Dockerfile
    image: couch-mint-obs-api
    restart: always
    depends_on:
      - couch-mint-postgres-db
    ports:
      - "8080:8080"
  couch-mint-postgres-db:
    image: postgres
    restart: always
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5433:${DB_PORT}'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}